# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Othello
version:      0.01
version_from: lib/Games/Othello.pm
installdirs:  site
requires:
    Exception::Class:              1.23
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
